### ISSUE TITLE
Can't build android version

### ISSUE THREAD

**Issue by aadanen** [JackZhen1324/TuneSync#5]
Hi!

I'm new to all this stuff so sorry in advance if im doing stuff wrong.

I cloned the repo, did 'yarn install', and then did npx expo run:android (but i get the same result if I use android studio).

The project fails to build, throwing the following output. Ill attach the whole file, but the main issue is:
Could not find com.android.tools.build:gradle:2.2.3.
[t.txt](https://github.com/user-attachments/files/16767852/t.txt)

when i look in maven (https://repo1.maven.org/maven2/com/android/tools/build/gradle/), there is no version 2.2.3
In the past, similar problems were solved by using jcenter instead(https://stackoverflow.com/questions/42403444/could-not-resolve-com-android-tools-buildgradle2-2-3). However, i think jcenter is no longer in use. as of a few days ago.
(https://jfrog.com/blog/jcenter-sunset/)

I'm not sure what to do because i think this specific package is no longer obtainable.

Thanks!
-aadanen

**Comment by JackZhen1324** [comment]
sure, looking on it

**Comment by JackZhen1324** [comment]
@gionathas Hi, let me know if this issue persist
